### ISSUE TITLE
Pure versions of createArchive and withArchive

### ISSUE THREAD

**Issue by themoritz** [mrkkrp/zip#13]
I'd love to have pure versions of `createArchive` and `withArchive` that work with, eg, `ByteString`s (maybe combined with conduit).

For example:

``` haskell
createArchiveBS :: ZipArchive a -> (ByteString, a)
withArchiveBS :: ByteString -> ZipArchive a -> (ByteString, a)
```

Do you have any plans for something like that?

**Comment by mrkkrp** [comment]
This is possible, but requires some effort and I'm not sure it's worth it. Currently the entire library is file-oriented because avoiding storing all the data in memory is actually the main motivation behind the package.

Do you know about [`zip-archive`](https://hackage.haskell.org/package/zip-archive)? It works purely and it's quite nice if you work with small files.

I will add the `feature-request` label, but it's unlikely that this feature will be added (at least with these signatures you provide).

Another option is to implement the whole thing as a conduit. So, for example you give `createArchive` a sink and then it streams archive contents there instead of saving them to a file. This is better, but may be difficult because normal creation of a zip file requires seeking in output. There is support for streaming in newer .ZIP specification though, so it's possible to *output* resulting archive in streaming fashion with some effort. Note that it's more difficult with consumption of archive contents, because we cannot easily locate end of central directory until we have entire archive, so we need to read it in and this again means intensive memory consumption.

So, at the end of the day, the library is file-oriented and for a good reason. Adding pure operations seems fine at first, but not very easy and rewording in practice.

**Comment by themoritz** [comment]
Thanks for your reply, I see your point about constant memory usage.

I'm using `zip-archive` at the moment and thought about switching over. My use-case is that we generate large XML strings using `xml-conduit`, zip them and then serve them with `servant`.

I was wondering if the whole process could be implemented using streams, so the conduit output option you mention would be very interesting.

**Comment by robertLeeGDM** [comment]
Output to a conduit sink would be useful where one's input is  from DB large objects and output is directly to HTTP. I have a need to auto generate such zip archives for web download. For now I can get by with file system access, but it would be nice to avoid it.

**Comment by robertLeeGDM** [comment]
See my other comment on Blind Archives as a way of partially solving this.

**Comment by mrkkrp** [comment]
Closing this one for now.

**Comment by robertLeeGDM** [comment]
Sorry about that.

On Thu, 2017-02-09 at 10:26 -0800, Mark Karpov wrote:
> Closing this one for now.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
>   
>   
> 
> 
> 
> 
> 
> 
> > > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/mrkkrp/zi
p","title":"mrkkrp/zip","subtitle":"GitHub
repository","main_image_url":"https://cloud.githubusercontent.com/ass
ets/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/mrkkrp/zip"}},"updates":{"snippets"
:[{"icon":"PERSON","message":"@mrkkrp in #13: Closing this one for
now."}],"action":{"name":"View
Issue","url":"https://github.com/mrkkrp/zip/issues/13#issuecomment-
278729152"}}}

**Comment by mrkkrp** [comment]
@robertLeeGDM Just to clarify, this is not the issue you opened, it's another one. Your issue about blind archives is still alive, and PR is alive too.

I closed this one because the thing it describes in unlikely to happen, unless you finish your PR, which is a different thing.
