### ISSUE TITLE
Generated zip files are less compatible than zip-archive's

### ISSUE THREAD

**Issue by yairchu** [mrkkrp/zip#14]
When generating a zip file with this package, it fails to extract in OS X 10.11.4 (newest), with both double-click in the Finder and with the `unzip` command line tool.

    $ unzip test.zip 
    Archive:  test.zip
       skipping: test                    need PK compat. v4.6 (can do v2.1)

One may download 7zip etc to extract it, but it's often desirable to create zip files that are compatible with common systems.
I ended up trying `zip-archive` and its generated zips extract fine, so I ended up using it.

**Comment by mrkkrp** [comment]
It looks like your program supports only features of 2.1 version of .ZIP specification. All tools that I tested (7Zip on Windows, `zip` and `unzip` on Linux) worked fine. Current version of spec is 6.3.4. This libarary supports features up to 4.6, so when an archive is created, the version is written in headers. Then your tools checks the headers and assumes that it cannot work with this archive. `zip-archive` always writes `2.1` unconditionally, because it only supports most basic things.

What I'm going to do is to choose “version required to unpack” according to actually used features, so this problem will be hopefully resolved.

Thanks for the report!

**Comment by mrkkrp** [comment]
@yairchu, This is fixed and Zip 0.1.2 is already on Hackage. Unless you use BZip2 compression or compress files larger than 4 GB, all tools should handle archives produced by the library just fine now.
