### ISSUE TITLE
No way to get entry as a Source/Sink

### ISSUE THREAD

**Issue by DuncanSands** [mrkkrp/zip#15]
I would like to do the following: stream data out of archive A1, transform it, and stream it into archive A2.  This would be easy if I could get the A1 entry as a conduit Source or the A2 entry as a conduit Sink.  For example, I could get the A1 entry as a Source, fuse it with my transforming Conduit, and pass the result to A2 sinkEntry.

In Codec.Archive.Zip.Internal there are routines producing a Source or Sink (sourceEntry and sinkEntry) but they are carefully hidden away, no idea why.  I'm hoping this means you can somehow get the same effect via some trick using the sourceEntry and sinkEntry routines in Codec.Archive.Zip, but I have no idea what the trick could be.

What is the reason for not exposing Codec.Archive.Zip.Internal.sourceEntry (resp sinkEntry)?  Any suggestions for how to get something equivalent?

**Comment by mrkkrp** [comment]
Hi, thanks for opening the issue. Indeed, there is no way to do this with current version of the library. The reason for not exporting low level sources and sinks is that this way we loose a lot of safety and it wouldn't play well with overall design of the library.

As you probably know from the docs, we do not perform modifications instantly, but rather collect them and perform actual actions on files when we leave the realm of `ZipArchive` monad or when `commit` function is called. This allows us to optimize how editing/creation of archive is performed and keep the whole thing safe and efficient.

`sourceEntry` and `sinkEntry` are low-level functions. They do their work but there is no way for them to know about context or protect user from wrong steps. Let me give an example. Zip archives have something called “central directory” at the end of file. This includes list of all files and some meta-information about them. With current design it's not possible to create invalid archive that would not have central directory or have it in corrupted state. If I give you raw source and sink helpers, I cannot make sure that you use them in the right way. You can just return them from `ZipArchive` monad and call them on your own. What's going to happen then? Maybe you will get a normal Zip file with an entry that goes *after* central directory generated by the library (and the entry itself will be missing from the central directory, but this is not really important since no software will be able to interpret such archive). With these low-level functions you could stream inside `ZipArchive` monad but the library doesn't work this way, it needs full “list of actions” so it can optimize and ensure everything is right. If I give you source and sink directly, everything will be broken.

My position here is that we should protect users from doing wrong things even at the price of some flexibility.

But solving your problem seems to be rather trivial. How about having `copyEntry'` or `copyEntryTransform` that would allow to pass it a conduit that will be used by the library to transform the data? I think it should do the trick.

**Comment by DuncanSands** [comment]
Thanks for replying.  Unfortunately the copyEntry' solution won't help with my immediate problem because I cheated in the description to make it simpler to explain: I do need to stream directly from a zip file entry and transform the data, but the sink isn't another zip-file, it's a complicated database layer which only provides a routine analogous to sinkEntry: one that takes a Source as an argument.

The reason it only provides such a routine is that turning the database layer into a real sink, while logically possible, is rather hard.  Presumably it is the same for you: it is probably logically possible to provide new routines that would present zip file entries as Sink/Source while interacting properly with the "list of actions" design (i.e. I'm not talking about just exposing the existing internal routines), but it would represent a lot of work.

Maybe it's easier to do something for the "archive entry as source" case.  That's all I need right now, and it sounds a lot easier than correctly handling the "archive entry as sink" case: for correctness don't you just need to ensure a "commit" happens before the first datum is streamed out?

**Comment by mrkkrp** [comment]
Providing source seems OK, because it doesn't edit anything and can be done at any moment.

**Comment by DuncanSands** [comment]
Being able to get an entry as a Source would be great.  But what should the semantics be if someone tries to stream from a zip file that they are in the middle of editing?

**Comment by mrkkrp** [comment]
This package uses my [`plan-b`](https://github.com/mrkkrp/plan-b) package. When file is edited, it's kept in temporary directory while original stays intact, and when we're done we rename edited version and it replaces original atomically, so it should not be much of a problem.

I will need to think carefully about possible caveats though.

**Comment by mrkkrp** [comment]
OK, we have `getEntrySource` now. It should work just fine because when file is edited, its new version is kept separately from original until it's time to replace the original. Replacement is *not* atomic though, but that shouldn't be a problem (normally).

**Comment by DuncanSands** [comment]
It seems to work fine.  Thanks a lot for fixing it!
